version: '3.4'
services:
    api.digital-maps.dev:
        container_name: api.digital-maps.dev
        image: nginx:1.19.2
        volumes:
            - ./build/nginx/nginx-local.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        networks:
            - bubble
        depends_on:
            - app.digital-maps.dev

    app.digital-maps.dev:
        container_name: app.digital-maps.dev
        build:
            context: ./
            dockerfile: Dockerfile
        env_file:
            - .env
        volumes:
            - ./:/app
        networks:
            - bubble
    mysql.digital-maps.dev:
        image: arm64v8/mysql:8.1.0
        ports:
          - "3306:3306"
        volumes:
          - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_USER: local
            MYSQL_PASSWORD: 123
            MYSQL_DATABASE: digital-maps
        networks:
          - bubble

volumes:
  mysql:
    driver: "local"

networks:
  bubble:
